# Generated by Django 4.1.4 on 2022-12-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VotingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('open_at', models.TimeField()),
                ('close_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('OIB', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('voting_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.votingplace')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('OIB', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('party', models.ManyToManyField(to='main.party')),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_ballot', models.TimeField()),
                ('id_of_ballot', models.CharField(max_length=10)),
                ('voted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidate')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.voter')),
            ],
        ),
    ]
